stages:
  - deploy

variables:
  CODE_DEPLOY_APP_NAME_DEV: "fedora-dev"
  CODE_DEPLOY_APP_NAME_PROD: "fedora-prod"
  CODE_DEPLOY_DEPLOYMENT_GROUP_DEV: "fedora-dev-auto"
  CODE_DEPLOY_DEPLOYMENT_GROUP_PROD: "fedora-prod-auto"
  S3_BUCKET: "fedora-code-deploy"
  S3_KEY_DEV: "fedora-code-deploy-dev.zip"
  S3_KEY_PROD: "fedora-code-deploy-prod.zip"
  
code-deploy:dev:
  stage: deploy
  when: manual
  allow_failure: false
  environment:
    name: dev
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  script:
    - aws deploy create-deployment
      --application-name ${CODE_DEPLOY_APP_NAME_DEV}
      --deployment-config-name CodeDeployDefault.OneAtATime
      --deployment-group-name ${CODE_DEPLOY_DEPLOYMENT_GROUP_DEV}
      --description "My dev deployment ${CI_COMMIT_SHA}"
      --s3-location bucket=${S3_BUCKET},bundleType=zip,key=${S3_KEY_DEV}
    - echo "Deployment successful"
  only:
    refs:
      - developer
    variables:
      - $AWS_ACCESS_KEY_ID && $AWS_SECRET_ACCESS_KEY && $AWS_DEFAULT_REGION

code-deploy:prod:
  stage: deploy
  when: manual
  allow_failure: false
  environment:
    name: prod
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  script:
    - aws deploy create-deployment
      --application-name ${CODE_DEPLOY_APP_NAME_PROD}
      --deployment-config-name CodeDeployDefault.OneAtATime
      --deployment-group-name ${CODE_DEPLOY_DEPLOYMENT_GROUP_PROD}
      --description "My prod deployment ${CI_COMMIT_SHA}"
      --s3-location bucket=${S3_BUCKET},bundleType=zip,key=${S3_KEY_PROD}
    - echo "Deployment successful"
  only:
    refs:
      - main
    variables:
      - $AWS_ACCESS_KEY_ID && $AWS_SECRET_ACCESS_KEY && $AWS_DEFAULT_REGION
