version: "3"

services:
  server:
    container_name: fedoraindia-api
    build:
      context: ./
      dockerfile: dockerfile
    environment:
      HOST: 0.0.0.0
    ports:
      - 5001:5001
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
        - redis

  redis:
    container_name: redis
    image: redis
    ports:
        - "6379:6379"

networks:
    dockernet:
      external: true
